/*
Enter your query here.
*/

/*
 * One linner
*/
SELECT CITY, LENGTH(CITY) FROM STATION WHERE 
CITY=(SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC LIMIT 1) OR
CITY=(SELECT CITY FROM STATION ORDER BY LENGTH(CITY) LIMIT 1);

/*
 * Two linner but faster
*/

SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) LIMIT 1;
